# Copyright Ripple Labs, 2019

version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - protobuf/install

      # Taken from: https://linuxize.com/post/install-java-on-debian-10/
      - run:
          name: 'Install Java'
          command: |
            sudo apt update
            wget https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/pool/main/a/adoptopenjdk-14-hotspot/adoptopenjdk-14-hotspot_14.0.0+36-2_amd64.deb
            sudo apt install ./adoptopenjdk-14-hotspot_14.0.0+36-2_amd64.deb

      - run:
          name: 'Install protoc plugin'
          command: |
            curl -L https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64 --output protoc-gen-grpc-web
            sudo mv protoc-gen-grpc-web /usr/local/bin/
            chmod +x /usr/local/bin/protoc-gen-grpc-web

      - run:
          name: 'Pull submodules'
          command: git submodule update --init --recursive

      - run:
          name: 'Install dependencies'
          command: |
            sudo npm -g i nyc codecov
            npm i
            npm rebuild

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: 'Compile Typescript'
          command: |
            npm run build

      - run:
          name: 'Webpack'
          command: npm run webpack

      - run:
          name: 'Run Tests'
          no_output_timeout: 60m
          command: |
            nyc npm test
