# Copyright Ripple Labs, 2019

version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:10.4.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - protobuf/install

      # Taken from: https://linuxize.com/post/install-java-on-debian-10/
      - run:
          name: "Install Java"
          command: |
            sudo apt update
            sudo apt install apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common
            wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
            sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
            sudo apt update
            sudo apt install adoptopenjdk-8-hotspot

      # Manually install maven because the version we need doesn't seem to be in a Debian package manager.
      # TODO(keefertaylor): Find a package repository that contains this.
      - run:
          name: "Install Maven"
          command: |
            wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P /tmp
            sudo tar xf /tmp/apache-maven-*.tar.gz -C /tmp
            sudo ln -s /tmp/apache-maven-3.6.3/bin/mvn /usr/bin/mvn

      - run:
          name: "Install protoc plugin"
          command: |
            curl -L https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64 --output protoc-gen-grpc-web
            sudo mv protoc-gen-grpc-web /usr/local/bin/
            chmod +x /usr/local/bin/protoc-gen-grpc-web

      - run:
          name: "Pull submodules"
          command: git submodule update --init --recursive

      - run:
          name: "Install dependencies"
          command: |
            sudo npm -g i nyc codecov
            npm i
            npm rebuild

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Compile Typescript"
          command: |
            npm run build

      - run:
          name: "Webpack"
          command: npm run webpack

      - run:
          name: "Run Tests"
          command: |
            nyc npm test

      - run:
          name: Code Coverage
          command: |
            mkdir coverage
            nyc report --reporter=text-lcov > coverage/coverage.json
            codecov
