# Copyright Ripple Labs, 2019

version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:10.4.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - protobuf/install

      - run:
          name: "Install Java"
          command: |
            sudo apt update
            sudo apt install default-jdk

      - run:
          name: "Install Maven"
          command: |
            wget http://mirrors.sonic.net/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
            tar -zxf apache-maven-3.2.5-bin.tar.gz
            sudo cp -R apache-maven-3.2.5 /usr/local
            sudo ln -s /usr/local/apache-maven-3.2.5/bin/mvn /usr/bin/mvn

      - run:
          name: "Install protoc plugin"
          command: |
            curl -L https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64 --output protoc-gen-grpc-web
            sudo mv protoc-gen-grpc-web /usr/local/bin/
            chmod +x /usr/local/bin/protoc-gen-grpc-web

      - run:
          name: "Pull submodules"
          command: git submodule update --init --recursive

      - run:
          name: "Install dependencies"
          command: |
            sudo npm -g i nyc codecov
            npm i
            npm rebuild

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: nyc npm test

      - run:
          name: Code Coverage
          command: |
            mkdir coverage
            nyc report --reporter=text-lcov > coverage/coverage.json
            codecov
